/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Cetecom
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniAgregarCliente = new javax.swing.JMenuItem();
        mniEditarCliente = new javax.swing.JMenuItem();
        mniEliminarCliente = new javax.swing.JMenuItem();
        mniListarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Clientes");

        mniAgregarCliente.setText("Agregar Cliente");
        mniAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAgregarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mniAgregarCliente);

        mniEditarCliente.setText("Editar Cliente");
        mniEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEditarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mniEditarCliente);

        mniEliminarCliente.setText("Eliminar Cliente");
        mniEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEliminarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mniEliminarCliente);

        mniListarCliente.setText("Listar Clientes");
        mniListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniListarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mniListarCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mniSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAgregarClienteActionPerformed
        // TODO add your handling code here:
        AgregarCliente ac = new AgregarCliente();
        ac.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_mniAgregarClienteActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEditarClienteActionPerformed
        // TODO add your handling code here:
        EditarCliente k = new EditarCliente();
        k.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEditarClienteActionPerformed

    private void mniEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEliminarClienteActionPerformed
        // TODO add your handling code here:
        EliminarCliente l = new EliminarCliente();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniEliminarClienteActionPerformed

    private void mniListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniListarClienteActionPerformed
        // TODO add your handling code here:
        ListarCliente lc = new ListarCliente();
        lc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mniListarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAgregarCliente;
    private javax.swing.JMenuItem mniEditarCliente;
    private javax.swing.JMenuItem mniEliminarCliente;
    private javax.swing.JMenuItem mniListarCliente;
    private javax.swing.JMenuItem mniSalir;
    // End of variables declaration//GEN-END:variables
}
